name: Release Automation

on:
  release:
    types: [created]

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Repartition ZIP
        run: |
          cd Mi439_repartition
          zip -r ../Mi439_repartition.zip ./*

      - name: Create Restore Partition ZIP
        run: |
          cd Mi439_restore_original_partition_table
          zip -r ../Mi439_restore_original_partition_table.zip ./*

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            Mi439_repartition.zip
            Mi439_restore_original_partition_table.zip
          asset_name: |
            Mi439_repartition.zip
            Mi439_restore_original_partition_table.zip
          asset_content_type: application/zip
