name: Release Automation

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Mi439_repartition.zip
      run: |
        cd Mi439_repartition
        zip -r ../Mi439_repartition.zip ./*
      shell: bash

    - name: Create Mi439_restore_original_partition_table.zip
      run: |
        cd Mi439_restore_original_partition_table
        zip -r ../Mi439_restore_original_partition_table.zip ./*
      shell: bash

    - name: Upload Mi439_repartition.zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Mi439_repartition.zip
        asset_name: Mi439_repartition.zip
        asset_content_type: application/zip
        
    - name: Upload Mi439_restore_original_partition_table.zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: Mi439_restore_original_partition_table.zip
        asset_name: Mi439_restore_original_partition_table.zip
        asset_content_type: application/zip
