name: Release Automation

on:
  release:
    types: [created]

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Repartition ZIP
        run: |
          cd Mi439_repartition
          zip -r ../Mi439_repartition.zip ./*

      - name: Create Restore Partition ZIP
        run: |
          cd Mi439_restore_original_partition_table
          zip -r ../Mi439_restore_original_partition_table.zip ./*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Mi439_repartition.zip
            Mi439_restore_original_partition_table.zip
